<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageReference Include="FluentAssertions" Version="8.10.0" />
    <PackageReference Include="MSTest.TestFramework" Version="4.2.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageReference Include="Reqnroll.NUnit" Version="3.3.4" />
    <PackageReference Include="Reqnroll.Tools.MsBuild.Generation" Version="3.3.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Qntm.Functions\Qntm.Functions.csproj" />
    <ProjectReference Include="..\Qntm.Gates\Qntm.Gates.csproj" />
    <ProjectReference Include="..\Qntm\Qntm.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Circuits\" />
  </ItemGroup>

</Project>
