// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace QuantTest.Features.Core
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("EntangledStatesTest")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class EntangledStatesTestFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Core", "EntangledStatesTest", "Тесты проверяют выполняются ли состояния Бэлла, GHZ и W\r\nТакие состояния нельзя п" +
                "олучить тензорным умножением матриц", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "EntangledStatesTest.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Core/EntangledStatesTest.feature.ndjson", 20);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Bell state")]
        [global::NUnit.Framework.TestCaseAttribute("90", "90", "match", "true", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("270", "270", "match", "true", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("90", "270", "opposed", "true", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("270", "90", "opposed", "true", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("90", "90", "match", "false", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("270", "270", "match", "false", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("90", "270", "opposed", "false", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("270", "90", "opposed", "false", "7", null)]
        public async global::System.Threading.Tasks.Task BellState(string a_Angle, string b_Angle, string measurmentResult, string mValue, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("A_Angle", a_Angle);
            argumentsOfScenario.Add("B_Angle", b_Angle);
            argumentsOfScenario.Add("MeasurmentResult", measurmentResult);
            argumentsOfScenario.Add("mValue", mValue);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Bell state", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Angle"});
                table1.AddRow(new string[] {
                            "A",
                            string.Format("{0}", a_Angle)});
                table1.AddRow(new string[] {
                            "B",
                            string.Format("{0}", b_Angle)});
#line 12
 await testRunner.GivenAsync("System has quantums", ((string)(null)), table1, "Given ");
#line hidden
#line 16
 await testRunner.AndAsync("Quantums \'A\' and \'B\' are entangled", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
 await testRunner.WhenAsync(string.Format("Measure to \'{0}\' quantum \'A\' in basis 0", mValue), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 18
 await testRunner.AndAsync("Measure quantum \'B\' in basis 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
 await testRunner.ThenAsync(string.Format("Measurment result of quantum \'A\' is \'{0}\' to measurment result of quantum \'B\'", measurmentResult), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("GHZ state")]
        [global::NUnit.Framework.TestCaseAttribute("90", "90", "90", "match", "true", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("270", "270", "270", "match", "true", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("90", "90", "90", "match", "false", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("270", "270", "270", "match", "false", "11", null)]
        public async global::System.Threading.Tasks.Task GHZState(string a_Angle, string b_Angle, string c_Angle, string measurmentResult, string mValue, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("A_Angle", a_Angle);
            argumentsOfScenario.Add("B_Angle", b_Angle);
            argumentsOfScenario.Add("C_Angle", c_Angle);
            argumentsOfScenario.Add("MeasurmentResult", measurmentResult);
            argumentsOfScenario.Add("mValue", mValue);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("GHZ state", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 33
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Angle"});
                table2.AddRow(new string[] {
                            "A",
                            string.Format("{0}", a_Angle)});
                table2.AddRow(new string[] {
                            "B",
                            string.Format("{0}", b_Angle)});
                table2.AddRow(new string[] {
                            "C",
                            string.Format("{0}", c_Angle)});
#line 34
await testRunner.GivenAsync("System has quantums", ((string)(null)), table2, "Given ");
#line hidden
#line 39
 await testRunner.AndAsync("Quantums \'A\' and \'B\' are entangled", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 40
 await testRunner.AndAsync("Quantums \'B\' and \'C\' are entangled", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
 await testRunner.AndAsync("Quantums \'A\' and \'C\' are entangled", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
 await testRunner.AndAsync("Ringify \'A\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
 await testRunner.WhenAsync(string.Format("Measure to \'{0}\' quantum \'A\' in basis 0", mValue), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 46
 await testRunner.AndAsync("Measure quantum \'B\' in basis 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
 await testRunner.AndAsync("Measure quantum \'C\' in basis 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
 await testRunner.ThenAsync(string.Format("Measurment result of quantum \'A\' is \'{0}\' to measurment result of quantum \'B\'", measurmentResult), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 49
 await testRunner.AndAsync(string.Format("Measurment result of quantum \'B\' is \'{0}\' to measurment result of quantum \'C\'", measurmentResult), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("W state")]
        [global::NUnit.Framework.TestCaseAttribute("70.5288", "70.5288", "70.5288", "true", "12", null)]
        [global::NUnit.Framework.TestCaseAttribute("70.5288", "70.5288", "70.5288", "false", "13", null)]
        public async global::System.Threading.Tasks.Task WState(string a_Angle, string b_Angle, string c_Angle, string mValue, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("A_Angle", a_Angle);
            argumentsOfScenario.Add("B_Angle", b_Angle);
            argumentsOfScenario.Add("C_Angle", c_Angle);
            argumentsOfScenario.Add("mValue", mValue);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("W state", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 67
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Angle"});
                table3.AddRow(new string[] {
                            "A",
                            string.Format("{0}", a_Angle)});
                table3.AddRow(new string[] {
                            "B",
                            string.Format("{0}", b_Angle)});
                table3.AddRow(new string[] {
                            "C",
                            string.Format("{0}", c_Angle)});
#line 68
await testRunner.GivenAsync("System has quantums", ((string)(null)), table3, "Given ");
#line hidden
#line 73
 await testRunner.AndAsync("Quantums \'A\' and \'B\' are entangled inverse", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
 await testRunner.AndAsync("Quantums \'B\' and \'C\' are entangled inverse", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
 await testRunner.AndAsync("Quantums \'A\' and \'C\' are entangled inverse", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
 await testRunner.WhenAsync(string.Format("Measure to \'{0}\' quantum \'A\' in basis 0", mValue), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 77
 await testRunner.AndAsync("Measure quantum \'B\' in basis 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
 await testRunner.AndAsync("Measure quantum \'C\' in basis 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
 await testRunner.ThenAsync("Measurment result corresponds to W state", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("A0B1 state does not exists")]
        [global::NUnit.Framework.TestCaseAttribute("90.0", "1.0", "48.1897", "3.0", "false", "A", "B", "0.0", "0", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("90.0", "1.0", "48.1897", "3.0", "true", "A", "B", "0.33333333", "5", "15", null)]
        [global::NUnit.Framework.TestCaseAttribute("90.0", "1.0", "48.1897", "3.0", "false", "B", "A", "0.0", "0", "16", null)]
        [global::NUnit.Framework.TestCaseAttribute("90.0", "1.0", "48.1897", "3.0", "true", "B", "A", "1.0", "0", "17", null)]
        public async global::System.Threading.Tasks.Task A0B1StateDoesNotExists(string a_Angle, string a_Value, string b_Angle, string b_Value, string mValue, string mFirstName, string mSecondName, string secondMeasurmentUnityProbability, string deviation, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("A_Angle", a_Angle);
            argumentsOfScenario.Add("A_Value", a_Value);
            argumentsOfScenario.Add("B_Angle", b_Angle);
            argumentsOfScenario.Add("B_Value", b_Value);
            argumentsOfScenario.Add("mValue", mValue);
            argumentsOfScenario.Add("mFirstName", mFirstName);
            argumentsOfScenario.Add("mSecondName", mSecondName);
            argumentsOfScenario.Add("secondMeasurmentUnityProbability", secondMeasurmentUnityProbability);
            argumentsOfScenario.Add("deviation", deviation);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A0B1 state does not exists", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 94
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Angle",
                            "Value"});
                table4.AddRow(new string[] {
                            "A",
                            string.Format("{0}", a_Angle),
                            string.Format("{0}", a_Value)});
                table4.AddRow(new string[] {
                            "B",
                            string.Format("{0}", b_Angle),
                            string.Format("{0}", b_Value)});
#line 95
await testRunner.GivenAsync("System has quantums", ((string)(null)), table4, "Given ");
#line hidden
#line 99
 await testRunner.AndAsync("Quantums \'A\' and \'B\' are entangled", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 100
 await testRunner.WhenAsync(string.Format("Measure to \'{0}\' quantum \'{1}\' in basis 0", mValue, mFirstName), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 101
 await testRunner.AndAsync(string.Format("Quantum \'{0}\' is measured 100 times in 0 basis", mSecondName), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 102
 await testRunner.AndAsync(string.Format("Measure quantum \'{0}\' in basis 0", mSecondName), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 103
 await testRunner.ThenAsync(string.Format("Quantum \'{0}\' probability corresponds to {1} with deviation of {2}", mSecondName, secondMeasurmentUnityProbability, deviation), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 104
 await testRunner.AndAsync("State \'A\' is 0 and \'B\' is 1 does not exists", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
