// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace QuantTest.Features.Core
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("MeasurmentTests")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class MeasurmentTestsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Core", "MeasurmentTests", "Измерения кваната под разными углами", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "MeasurmentTests.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Core/MeasurmentTests.feature.ndjson", 33);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Measurment must give correct propability")]
        [global::NUnit.Framework.TestCaseAttribute("0", "0", "0", "0", "0", null)]
        [global::NUnit.Framework.TestCaseAttribute("90", "0", "0.5", "10", "1", null)]
        [global::NUnit.Framework.TestCaseAttribute("180", "0", "1", "0", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("270", "0", "0.5", "10", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("360", "0", "0", "0", "4", null)]
        [global::NUnit.Framework.TestCaseAttribute("0", "90", "0.5", "10", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("90", "90", "0", "0", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("180", "90", "0.5", "10", "7", null)]
        [global::NUnit.Framework.TestCaseAttribute("270", "90", "1", "0", "8", null)]
        [global::NUnit.Framework.TestCaseAttribute("360", "90", "0.5", "10", "9", null)]
        [global::NUnit.Framework.TestCaseAttribute("120", "0", "0.75", "10", "10", null)]
        [global::NUnit.Framework.TestCaseAttribute("240", "0", "0.75", "10", "11", null)]
        [global::NUnit.Framework.TestCaseAttribute("0", "120", "0.75", "10", "12", null)]
        [global::NUnit.Framework.TestCaseAttribute("240", "120", "0.75", "10", "13", null)]
        [global::NUnit.Framework.TestCaseAttribute("0", "240", "0.75", "10", "14", null)]
        [global::NUnit.Framework.TestCaseAttribute("120", "240", "0.75", "10", "15", null)]
        public async global::System.Threading.Tasks.Task MeasurmentMustGiveCorrectPropability(string qangle, string mangle, string uprobalility, string deviation, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("qangle", qangle);
            argumentsOfScenario.Add("mangle", mangle);
            argumentsOfScenario.Add("uprobalility", uprobalility);
            argumentsOfScenario.Add("deviation", deviation);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Measurment must give correct propability", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 5
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Angle"});
                table5.AddRow(new string[] {
                            "A",
                            string.Format("{0}", qangle)});
#line 6
 await testRunner.GivenAsync("System has quantums", ((string)(null)), table5, "Given ");
#line hidden
#line 9
 await testRunner.WhenAsync(string.Format("Quantum \'A\' is measured 10000 times in {0} basis", mangle), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
 await testRunner.ThenAsync(string.Format("Quantum \'A\' probability corresponds to {0} with deviation of {1}", uprobalility, deviation), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Measurment must give correct angle")]
        [global::NUnit.Framework.TestCaseAttribute("0", "0", "false", "0", "16", null)]
        [global::NUnit.Framework.TestCaseAttribute("70.5288", "0", "false", "0", "17", null)]
        [global::NUnit.Framework.TestCaseAttribute("70.5288", "0", "true", "180", "18", null)]
        [global::NUnit.Framework.TestCaseAttribute("90.0", "0", "false", "0", "19", null)]
        [global::NUnit.Framework.TestCaseAttribute("90.0", "0", "true", "180", "20", null)]
        [global::NUnit.Framework.TestCaseAttribute("109.4712", "0", "false", "0", "21", null)]
        [global::NUnit.Framework.TestCaseAttribute("109.4712", "0", "true", "180", "22", null)]
        [global::NUnit.Framework.TestCaseAttribute("180.0", "0", "true", "180", "23", null)]
        [global::NUnit.Framework.TestCaseAttribute("250.5288", "0", "false", "0", "24", null)]
        [global::NUnit.Framework.TestCaseAttribute("250.5288", "0", "true", "180", "25", null)]
        [global::NUnit.Framework.TestCaseAttribute("270.0", "0", "false", "0", "26", null)]
        [global::NUnit.Framework.TestCaseAttribute("270.0", "0", "true", "180", "27", null)]
        [global::NUnit.Framework.TestCaseAttribute("289.4712", "0", "false", "0", "28", null)]
        [global::NUnit.Framework.TestCaseAttribute("289.4712", "0", "true", "180", "29", null)]
        [global::NUnit.Framework.TestCaseAttribute("360", "0", "false", "0", "30", null)]
        public async global::System.Threading.Tasks.Task MeasurmentMustGiveCorrectAngle(string qangle, string measureAngle, string measureResult, string resultAngle, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("qangle", qangle);
            argumentsOfScenario.Add("measureAngle", measureAngle);
            argumentsOfScenario.Add("measureResult", measureResult);
            argumentsOfScenario.Add("resultAngle", resultAngle);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Measurment must give correct angle", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 33
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Angle"});
                table6.AddRow(new string[] {
                            "A",
                            string.Format("{0}", qangle)});
#line 34
 await testRunner.GivenAsync("System has quantums", ((string)(null)), table6, "Given ");
#line hidden
#line 37
 await testRunner.WhenAsync(string.Format("Quantum \'A\' is measured to \'{0}\' in {1} basis", measureResult, measureAngle), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 38
 await testRunner.ThenAsync(string.Format("Quantum \'A\' angle corresponds to {0}", resultAngle), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
