// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace QuantTest.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("BB84")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class BB84Feature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "BB84", "Проверка работы протокола передачи ключей BB84", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "BB84.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/BB84.feature.ndjson", 4);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("BB84 key transmittion without intercept")]
        [global::NUnit.Framework.CategoryAttribute("BB84")]
        public async global::System.Threading.Tasks.Task BB84KeyTransmittionWithoutIntercept()
        {
            string[] tagsOfScenario = new string[] {
                    "BB84"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BB84 key transmittion without intercept", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await testRunner.GivenAsync("Alice generates 4n size key where n is 1000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
await testRunner.AndAsync("\'Alice\' chose basis for each bit in the key", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
await testRunner.AndAsync("\'Bob\' chose basis for each bit in the key", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
await testRunner.AndAsync("Alice makes quantums stream", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
await testRunner.WhenAsync("Alice sends quantums stream to Bob", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
await testRunner.AndAsync("Alice and Bob compares their basises in unencripted form", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
await testRunner.AndAsync("Bob measure quantums stream with chosen basises for each quantum", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
await testRunner.AndAsync("\'Alice\' leave key bits that corresponds to coinciding basises", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
await testRunner.AndAsync("\'Bob\' leave key bits that corresponds to coinciding basises", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
await testRunner.AndAsync("Alice and Bob compares one half of their key bits in unencripted form", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
await testRunner.ThenAsync("Compared key bits are identical", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 18
await testRunner.AndAsync("Alice and Bob keys are identical", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("BB84 key transmittion with intrusion")]
        [global::NUnit.Framework.CategoryAttribute("BB84")]
        public async global::System.Threading.Tasks.Task BB84KeyTransmittionWithIntrusion()
        {
            string[] tagsOfScenario = new string[] {
                    "BB84"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("BB84 key transmittion with intrusion", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 21
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 22
await testRunner.GivenAsync("Alice generates 4n size key where n is 1000", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 23
await testRunner.AndAsync("\'Alice\' chose basis for each bit in the key", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
await testRunner.AndAsync("\'Bob\' chose basis for each bit in the key", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
await testRunner.AndAsync("Alice makes quantums stream", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
await testRunner.WhenAsync("Alice sends quantums stream to Bob", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 31
await testRunner.AndAsync("\'Eva\' chose basis for each bit in the key", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
await testRunner.AndAsync("Eva intercepts transmittion", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
await testRunner.AndAsync("Alice and Bob compares their basises in unencripted form", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
await testRunner.AndAsync("Bob measure quantums stream with chosen basises for each quantum", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
await testRunner.AndAsync("\'Alice\' leave key bits that corresponds to coinciding basises", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
await testRunner.AndAsync("\'Bob\' leave key bits that corresponds to coinciding basises", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
await testRunner.AndAsync("Alice and Bob compares one half of their key bits in unencripted form", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 38
await testRunner.ThenAsync("Compared key bits are not identical and differ for 1/4 with deviation of 10", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 39
await testRunner.AndAsync("Alice and Bob keys are not identical", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
